export const SET_POPULAR_MOVIES = 'SET_POPULAR_MOVIES';
export const SET_TOP_RATED_MOVIES = 'SET_TOP_RATED_MOVIES';
export const SET_UPCOMING_MOVIES = 'SET_UPCOMING_MOVIES';
export const SET_MOVIE_DETAILS = 'SET_MOVIE_DETAILS';
export const SET_MOVIE_CAST = 'SET_MOVIE_CAST';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SEARCHED_MOVIES = 'SEARCHED_MOVIES';